###
GET http://localhost:8080/api/inventarios HTTP/1.1


###
POST http://localhost:8080/api/inventarios HTTP/1.1
Content-Type: application/json

{
    "serial": "487553",
    "modelo": "model4871",
    "descripcion": "Pc escritorio",
    "fotoEquipo": "http://mifoto.com",
    "color": "Negro",
    "precio": 2000,
    "usuario": "62840c4e9e67fc8ebe7a232b",
    "marca": "62894d992fe42a7a9552078d",
    "estadoEquipo": "62879049dce159b84e53ee2a",
    "tipoEquipo": "6286d63374ede0ce6bd4ac23"
}


###
PUT http://localhost:8080/api/inventarios/628962d28e0a19d93809b0f8 HTTP/1.1
Content-Type: application/json

{
    "serial": "4875245",
    "modelo": "model487",
    "descripcion": "pc portatil",
    "fotoEquipo": "http://mifoto.com",
    "color": "verde",
    "precio": 2000,
    "usuario": "62840c4e9e67fc8ebe7a232b",
    "marca": "62894d992fe42a7a9552078d",
    "estadoEquipo": "62879049dce159b84e53ee2a",
    "tipoEquipo": "6286d63374ede0ce6bd4ac23"
}


###
DELETE http://localhost:8080/api/inventarios/628962d28e0a19d93809b0f8 HTTP/1.1