###
GET http://localhost:8080/api/marcas HTTP/1.1


###
POST http://localhost:8080/api/marcas HTTP/1.1
Content-Type: application/json

{
    "nombre": "Lg"
}


###
PUT http://localhost:8080/api/marcas/62879ec61c63dcff9d51d460 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Acer"
}


###
DELETE http://localhost:8080/api/marcas/62879ec61c63dcff9d51d460 HTTP/1.1