###
GET http://localhost:8080/api/tipoEquipos HTTP/1.1


###
POST http://localhost:8080/api/tipoEquipos HTTP/1.1
Content-Type: application/json

{
    "nombre": "Movil"
}


###
PUT http://localhost:8080/api/tipoEquipos/6286d63374ede0ce6bd4ac23 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Computo"
}


###
DELETE http://localhost:8080/api/tipoEquipos/6286d1fde2d8b2c6c206794a HTTP/1.1