###
GET http://localhost:8080/api/usuarios HTTP/1.1


###
POST http://localhost:8080/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "nombre": "Homero Salazar",
    "email": "hsalazar@email.com"
}


###
PUT http://localhost:8080/api/usuarios/62840c4e9e67fc8ebe7a232b HTTP/1.1
Content-Type: application/json

{
    "nombre": "Juan Diego Salazar",
    "email": "jsalavel@mail.com",
    "estado" : true
}


###
DELETE http://localhost:8080/api/usuarios/6286b992efdf7701bf0a6c2a HTTP/1.1


