###
GET http://localhost:8080/api/usuarios HTTP/1.1


###
PUT http://localhost:8080/api/usuarios/6284197026e8d923e2b1938a HTTP/1.1
Content-Type: application/json

{
    "nombre": "Antonio Salazar",
    "email": "antonio@mail.com"
}


###
POST http://localhost:8080/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "nombre": "Rafael Salazar",
    "email": "rafsage@mail.com"
}


###
DELETE http://localhost:8080/api/usuarios/62840cb1e9f279e7b46a3863 HTTP/1.1


